spring:
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect


  mail:
    host: localhost
    port: 1025
    username:
    password:

  booking-confirmation:
    subject: "Подтверждение брони бассейна"
    body: |
      Ваша бронь подтверждена!
      Бассейн: %s
      Время начала: %s

  datasource:
    url: jdbc:postgresql://localhost:5432/pool
    username: root
    password: 1029
    driver-class-name: org.postgresql.Driver

  liquibase:
    change-log: classpath:/db/db.changelog-master.xml
    enabled: true

#logging:
#  level:
#    root: WARN
#    com.poolapp.pool.service.impl: DEBUG

logging:
  level:
    root: WARN
    com.poolapp.pool.service.impl: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE


jwt:
  signing-key: "9vJsoj+ls24tEyJS0PV64P3pNuNJvsG5fxjKrfstPqU="
  access-token-expiration-ms: 900000
  refresh-token-expiration-ms: 604800000